### ISSUE TITLE
"miyagi new" with "--only" parameter works differently than documented

### ISSUE THREAD

**Issue by mvsde** [mgrsskls/miyagi#183]
**Describe the bug**
The documentation explains the `--only` parameters like this:

```sh
miyagi new <folderName>/<componentName> --only=tpl,docs
```

(https://docs.miyagi.dev/cli-commands/creating-a-component/#-only)

This only works if only one file type is specified (e.g. `--only=tpl`). If more than one file is specified (e.g. `--only=tpl,docs`) than the component folder will be empty.

**Expected behavior**
A component folder with all the specified files is created.

**Additional context**
The code expects the `--only` parameter to arrive as an array:

https://github.com/mgrsskls/miyagi/blob/dfcbf34f864398ce04d4388a9d6df951d1e54c72/packages/core/lib/generator/component.js#L64-L66

This only works for more than one file if multiple `--only`s are specified like this:

```sh
miyagi new <folderName>/<componentName> --only=tpl --only=docs
```

**Comment by mgrsskls** [comment]
Hey @mvsde, thanks! I think I must have missed a breaking change in a dependency there, that definitely worked before … 😅 Anyway, it works when separating them by space instead of comma, like this:

```bash
miyagi new <folderName>/<componentName> --only=tpl docs
```

As this is done by `yargs`, I think I would keep it like this and simply update the docs.

Or do you think comma separated would be better?

**Comment by mvsde** [comment]
I didn’t know yargs also supports the space variant. Nice!

I would simply update the docs and no longer support the comma-separated version. That’s _technically_ a breaking change, but since nobody filed an issue until now this shouldn’t be that big of a deal 🤷🏻

**Comment by mgrsskls** [comment]
That's the joy when (almost) no one uses your OSS :D Docs are updated, thanks!
