### ISSUE TITLE
"miyagi lint path/to/component" always exits with 0

### ISSUE THREAD

**Issue by mvsde** [mgrsskls/miyagi#184]
**Describe the bug**
Linting a single component always exits the process with code `0`. Even when the component has invalid schema/mock data.

**To Reproduce**
1. Create invalid mock data for a component.
2. Lint this component with `miyagi lint path/to/component`.

**Expected behavior**
The process exits with error code `1` (like when linting all files with `miyagi lint`).

**Comment by mgrsskls** [comment]
Fixed in https://github.com/mgrsskls/miyagi/commit/252d5867b3d8182e82d28126370a4a6895ca0f69
